const TIPO_VALOR={
    DECIMAL:       'VAL_DECIMAL',
    CADENA:        'VAL_CADENA',
    BANDERA:       'VAL_BANDERA',
    CARACTER:      'VAL_CARACTER',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR',
    ENTERO:        'VAL_ENTERO'
}

module.exports = TIPO_VALOR